### ISSUE TITLE
GET Query arguments are not sent to server

### ISSUE THREAD

**Issue by massenz** [ivere27/SimpleHttpRequest#2]
I am using `SimpleHttpRequest` in my tests for my [SimpleApiServer](https://github.com/massenz/SimpleApiServer) and these were failing to assert on parsing query args.

However, it turns out that this client does not send the query args in the given URL:
```
        client_.get("http://localhost:7999/api/v1/query?abc=test&def=value")
                .on("error", [](request::Error &&err) {
                    FAIL() << "Could not connect to API Server: "
                           << err.message;
                }).on("response", [this](request::Response &&res) {
                    EXPECT_EQ(200, res.statusCode) << res.str();
                }).end();
```
would always fail, as the test rig returns a `400` if it doesn't receive the `abc` and `def` query args.

Tried against a very simple Flask server, and using Postman I get:
```
URL: http://localhost:5050/demo?bar=what+to+do+now&foo=9987&zaz=%2F%40
Logs:
ImmutableMultiDict([('bar', u'what to do now'), ('foo', u'9987'), ('zaz', u'/@')])
```
but with the same code as above, the logs show:
```
ImmutableMultiDict([])
```

Is this "expected behavior"? as I sure was surprised (and spent a lot of time, thinking it was my code being buggy 😆 )

**Comment by ivere27** [comment]
Happy New Year!(soon)
it seems there's a bug of query arguments.
I'll have a look.

**Comment by ivere27** [comment]
@massenz 
could you try the commit https://github.com/ivere27/SimpleHttpRequest/commit/8d2a3782979b8983175ca7d2347a7d74b1a23c3e

sorry about the bug :hushed:

**Comment by massenz** [comment]
Awesome, that worked! :clap: 
This fixes [my test](https://github.com/massenz/SimpleApiServer/commit/5e510d3a9a87525830e9175d317f6566cd95c3f6).

> sorry about the bug

Not at all! thanks for the super-quick fix.
(and also for inspiring me to write `SimpleApiServer` :smile: )
